// Bundle the API's own source into a single runnable file: dist/server.js.
//
// Run with:  npm run build        (then: npm start  ->  node dist/server.js)
//
// WHY dist/ SITS BESIDE src/, NOT INSIDE IT
//   Every path in this codebase is resolved relative to the running file:
//     db/firms/news/screener.js   ROOT = __dirname/../../..   -> repo root
//     server.js                   ../.env  and  ../certs      -> src/nodejs/
//   dist/ is at the SAME depth as src/, so all of those resolve to exactly the
//   same places from the bundle as from source. Nest dist/ any deeper (or move
//   it to the repo root) and the API would silently read the wrong data
//   directory and fail to find .env and the TLS certificate. If this output
//   path ever changes, those six resolutions must change with it.
//
// WHY DEPENDENCIES STAY EXTERNAL (packages: 'external')
//   @duckdb/node-api loads a NATIVE binary (@duckdb/node-bindings-win32-x64/
//   duckdb.node). A bundler cannot inline a .node file, and rewriting the
//   loader's require path breaks it. Since node_modules must therefore be
//   present at runtime regardless, there is nothing to gain from inlining
//   express or cheerio either — so all packages resolve from node_modules and
//   only our own modules get bundled. This is the normal shape for a Node
//   backend; it is not a workaround.
//
// NOT MINIFIED, deliberately: a server gains no load-time benefit from it and
// it turns every production stack trace into noise. Source maps are emitted so
// traces point back at src/.

import { build } from 'esbuild';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(await readFile(path.join(HERE, 'package.json'), 'utf8'));

const result = await build({
  entryPoints: [path.join(HERE, 'src', 'server.js')],
  outfile: path.join(HERE, 'dist', 'server.js'),
  bundle: true,
  platform: 'node',
  // ESM out, because the source is ESM ("type": "module") and uses
  // import.meta.url — which has no meaning in CJS and would have to be shimmed.
  format: 'esm',
  // Match the installed runtime so esbuild leaves modern syntax alone rather
  // than downlevelling it for engines we never run on.
  target: `node${process.versions.node.split('.')[0]}`,
  packages: 'external',
  sourcemap: true,
  logLevel: 'info',
  metafile: true,
  banner: {
    js: `// ${pkg.name} v${pkg.version} — bundled ${new Date().toISOString()}\n`
      + `// Generated by build.js. Do not edit; edit src/ and rebuild.`,
  },
});

// Report what actually went in, so an accidentally-inlined native module or a
// forgotten source file is visible at build time instead of at 3am.
const out = Object.entries(result.metafile.outputs).find(([f]) => f.endsWith('server.js'));
if (out) {
  const [file, meta] = out;
  const own = Object.keys(meta.inputs).filter((f) => !f.includes('node_modules'));
  console.log(`\nbundled ${own.length} source files -> ${file} (${(meta.bytes / 1024).toFixed(1)} KiB)`);
  for (const f of own.sort()) console.log(`  ${f}`);
}
